config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'procesos#index'

  resources :procesos
  resources :questions
end

app/models/postulant.rb
class Postulant < ActiveRecord::Base
	belongs_to :proceso
	
end

app/models/proceso.rb
class Proceso < ActiveRecord::Base
  belongs_to :user
  has_many :questions
  has_many :referees
  has_many :postulants
  
  
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :proceso
	has_one :Question_category
end

app/models/question_category.rb
class QuestionCategory < ActiveRecord::Base
	belongs_to :question
end

app/models/referee.rb
class Referee < ActiveRecord::Base
	belongs_to :preceso
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :procesos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/procesos_controller.rb
class ProcesosController < ApplicationController
  before_action :find_note, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  def index
  @procesos = Proceso.where(user_id: current_user)
  end

  def show
    
  end

  def new
    #@proceso = Proceso.new
   @proceso = current_user.procesos.build

  end

  def create
    @proceso = current_user.procesos.build(proceso_params)

    if @proceso.save
      redirect_to @proceso
    else 
      render 'new'
    end
  end

    def update
    if @proceso.update(proceso_params)
      redirect_to @proceso
    else
      render 'edit'
  end
end

  def destroy
    @proceso.destroy
    redirect_to procesos_path
  end

  private

  def find_note
    @proceso = Proceso.find(params[:id])
  end

  def proceso_params
    params.require(:proceso).permit(:name, :description, :function, :workplace, :deadline, :email, :state, :color, :company_logo )
  end



end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_note, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
  @questions = Question.all.order("created_at DESC")
  end

  def show
    
  end

  def new
    #@proceso = Proceso.new
   #@question = current_user.questions.build
   @question = Question.new

  end

  def create
    @question = Question.new(question_params)
    #@question = current_user.questions.build

    if @question.save
      redirect_to @question
    else 
      render 'new'
    end
  end

    def update
    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
  end
end

  def destroy
    @question.destroy
    redirect_to questions_path
  end

  private

  def find_note
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :description, :time )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/procesos_helper.rb
module ProcesosHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Task
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true 
  = javascript_include_tag 'application', 'data-turbolinks-track' => true 
  = csrf_meta_tags 
%body
  %header
    .header_inner
      = link_to image_tag('logo.jpg'), root_path, id:"logo"
      %nav
        -# - if user_signed_in?
        -#   -# - if can? :manage, :all
        -#     = link_to "New Note", new_note_path
        -#   %end
        -#   = link_to "Sign Out", destroy_user_session_path, method: :delete
        -# - else
        -#   = link_to "Log In", new_user_session_path
  %p.notice= notice
  %p.alert= alert

  = yield

app/views/procesos/_form.html.haml
.wrapper_with_padding
  = simple_form_for @proceso do |f|
    = f.input :name
    = f.input :description
    = f.input :function
    = f.input :workplace
    = f.input :deadline
    = f.input :email
    = f.input :state
    = f.input :color
    -# = f.input :company_logo
    = f.button :submit

app/views/procesos/index.html.haml
.wrapper_with_padding
  %h3 Procesos de selección
  %buttom= link_to "New Precess", new_proceso_path, class: "button"

  #notes.clearfix
    - unless @procesos.blank?
      - @procesos.each do |proceso|
        %a{href:(url_for [proceso])}
          .note
            %h2.title= proceso.name
            %p.title= proceso.state
            
    - else
      %h2 Add a note
      %p It appears you haven't created any notes yet... Lets fix that. Why don't you create a new note below
      %buttom= link_to "New Precess", new_proceso_path
%h1 Preguntas  

= render partial: 'questions/form'

app/views/procesos/new.html.haml
%h1 Add a New Process
= render 'form'

app/views/procesos/show.html.haml
.wrapper_with_padding
  #note_show
    %h1.title= @proceso.name
    %p lugar
    %p= @proceso.description
    %p= @proceso.function
    %p= @proceso.workplace
    %p= @proceso.deadline
    %p= @proceso.email
    %p= @proceso.state
    %p= @proceso.color

    .buttons
    
      -# = link_to "ALL Notes", notes_path, class: "button"
      -# = link_to "Edit", edit_note_path(@note), class: "button"
      -# = link_to "Delete", note_path(@note), method: :delete, data: {confirm: "Are you sure?"}, class: "button"
    %end

app/views/questions/_form.html.haml
.wrapper_with_padding
  = simple_form_for Question.new do |f|
    = f.input :title
    = f.input :description
    = f.input :time
    -# = f.input :company_logo
    = f.button :submit

app/views/questions/index.html.haml
.wrapper_with_padding
  %h3 Procesos de selección
  %buttom= link_to "New Question", new_question_path, class: "button"

  #notes.clearfix
    - unless @questions.blank?
      - @questions.each do |question|
        %a{href:(url_for [question])}
          .note
            %h2.title= question.name
            %p.title= question.state
            
    - else
      %h2 Add a note
      %p It appears you haven't created any notes yet... Lets fix that. Why don't you create a new note below
      %buttom= link_to "New Precess", new_question_path

app/views/questions/new.html.haml
%h1 Add a New Question
= render 'form'

app/views/questions/show.html.haml
.wrapper_with_padding
  #note_show
    %h1.title= @question.title
    %p lugar
    %p= @question.description
    %p= @question.time
 
    .buttons
    
      -# = link_to "ALL Notes", notes_path, class: "button"
      -# = link_to "Edit", edit_note_path(@note), class: "button"
      -# = link_to "Delete", note_path(@note), method: :delete, data: {confirm: "Are you sure?"}, class: "button"
    %end